version: "3.8"
services:
  kitchen_service_container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
        - .:/app
    depends_on:
     - kitchen_db_container

  kitchen_db_container:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: kitchen_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33060:3306
